# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 13:46
from __future__ import unicode_literals

import app.market.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Категория')),
                ('slug', models.SlugField(null=True, verbose_name='URL')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'ordering': ['sort_index'],
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('articul', models.CharField(max_length=256, null=True, verbose_name='Артикул товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фотографию обложки')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('popularity_index', models.PositiveIntegerField(default=0, verbose_name='Индекс популярности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_main', models.BooleanField(default=False, verbose_name='Выводить на главной')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('meta_keywords', models.TextField(blank=True, null=True, verbose_name='meta keywords')),
                ('category', models.ManyToManyField(related_name='goods_categories', to='market.Category', verbose_name='Категория товаров')),
                ('related_goods', models.ManyToManyField(blank=True, related_name='_goods_related_goods_+', to='market.Goods', verbose_name='Похожие товары')),
            ],
            options={
                'verbose_name': 'Товар',
                'ordering': ['sort_index'],
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='GoodsConsist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_item', models.CharField(max_length=128, verbose_name='Пункт состава')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_consist', to='market.Goods', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Пункт состава',
                'ordering': ['sort_index'],
                'verbose_name_plural': 'Пункты состава',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='tag',
            field=models.ManyToManyField(related_name='goods_tag', to='market.Tag', verbose_name='Метка'),
        ),
    ]
