# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 23:34
from __future__ import unicode_literals

import app.market.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_goods_shot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать иконку слайда'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_active',
            field=models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать иконку активного слайда'),
        ),
        migrations.AddField(
            model_name='goods',
            name='discount_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена со скидкой'),
        ),
    ]
