# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20171207_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Анотация'),
        ),
    ]
