# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 23:52
from __future__ import unicode_literals

import app.market.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0003_auto_20171207_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать иконку слайда')),
                ('icon_active', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать иконку активного слайда')),
                ('discount', models.CharField(max_length=128, verbose_name='Размер скидки')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
            ],
            options={
                'verbose_name_plural': 'Слайды скидки',
                'verbose_name': 'Слайд скидки',
                'ordering': ['sort_index'],
            },
        ),
        migrations.CreateModel(
            name='DiscountSliderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('discount_slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_goods', to='mainpage.DiscountSlider', verbose_name='Слайдер')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_goods', to='market.Goods', verbose_name='Товар cо скидкой')),
            ],
            options={
                'verbose_name_plural': 'Товары слайда скидки',
                'verbose_name': 'Товар слайда скидки',
                'ordering': ['sort_index'],
            },
        ),
        migrations.CreateModel(
            name='ExampleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.market.models.upload_to, verbose_name='Изображение')),
                ('sorting', models.PositiveIntegerField(blank=True, default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name_plural': 'Фотографии примеров наших блюд',
                'verbose_name': 'Фотография примера наших блюд',
                'ordering': ['sorting'],
            },
        ),
        migrations.CreateModel(
            name='GoodsPopular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_popular_goods', to='market.Goods', verbose_name='Популярный товар')),
            ],
            options={
                'verbose_name_plural': 'Популярные товары',
                'verbose_name': 'Популярный товар',
                'ordering': ['sort_index'],
            },
        ),
        migrations.CreateModel(
            name='GoodsRapid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_rapid_goods', to='market.Goods', verbose_name='Срочный товар')),
            ],
            options={
                'verbose_name_plural': 'Срочные товары',
                'verbose_name': 'Срочный товар',
                'ordering': ['sort_index'],
            },
        ),
        migrations.CreateModel(
            name='MainAboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_item', models.CharField(max_length=128, verbose_name='Текст "О нас"')),
                ('image', models.ImageField(blank=True, upload_to=app.market.models.upload_to, verbose_name='Выбрать фото "О нас"')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Индекс сортировки')),
            ],
            options={
                'verbose_name_plural': 'Пункты "О нас"',
                'verbose_name': 'Пункт "О нас"',
                'ordering': ['sort_index'],
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Главная',
                'verbose_name': 'Главная',
            },
        ),
        migrations.AddField(
            model_name='mainaboutus',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_about', to='mainpage.MainPage', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='goodsrapid',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapid_goods', to='mainpage.MainPage', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='goodspopular',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_goods', to='mainpage.MainPage', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='exampleimage',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_images', to='mainpage.MainPage', verbose_name='Фото для примеров блюд'),
        ),
        migrations.AddField(
            model_name='discountslider',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_mains', to='mainpage.MainPage', verbose_name='Страница'),
        ),
    ]
