# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsrapid',
            options={'ordering': ['sort_index'], 'verbose_name': 'Товар "Прямо сейчас"', 'verbose_name_plural': 'Товары "Прямо сейчас"'},
        ),
        migrations.AlterField(
            model_name='mainaboutus',
            name='text_item',
            field=models.TextField(max_length=128, verbose_name='Текст "О нас"'),
        ),
    ]
