# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя и фамилия'),
        ),
    ]
